install:
	cl /nologo /GS- /c "cAsyncIO.c" /Fo"cAsyncIO.obj"
	cl /nologo /GS- /c "hashtable.c" /Fo"hashtable.obj"
	move cAsyncIO.obj "..\..\libraries\OS-Windows\Clean System Files\" >nul
	move hashtable.obj "..\..\libraries\OS-Windows\Clean System Files\" >nul
