
CC = x86_64-w64-mingw32-gcc
CFLAGS = -DI486 -D_WINDOWS_ -DG_AI64 -O -fomit-frame-pointer

OBJECTS = cg.o cgcalc.o cgcode.o cginput.o cginstructions.o \
	cglin.o cgopt.o cgaas.o cgawas.o cgstack.o

cg.exe: $(OBJECTS)
	$(CC) -s $(OBJECTS) -o $@

clean:
	rm $(OBJECTS)

# DO NOT DELETE
