
CC = gcc
CFLAGS = -m32 -DI486 -DGNU_C -DLINUX -DLINUX_ELF -O -fomit-frame-pointer

OBJECTS = cg.o cgcalc.o cgcode.o cginput.o cginstructions.o \
	cglin.o cgopt.o cgias.o cgiwas.o cgstack.o

cg: $(OBJECTS)
	gcc -m32 -s $(OBJECTS) -o $@

clean:
	rm $(OBJECTS)

# DO NOT DELETE
