del istartup.a
del istartup.b
del istartup.cpp
del wcon.a
del wcon.s
del iprofile.a
del iprofile.cpp
del ifileIO3.a
del ifileIO3_.s
del ifileIO3.cpp
del wfileIO3.a
del wfileIO3.s
del _startup1.s
del _startup1.go
del _startup2.s
del _startup2.go
del itrace.a
del itrace.cpp
del wcon_imports.a
del wcon_imports.cpp
