CC=gcc
OBJS:=bsearch.o systemsignal.o systemprocess.o WCsubst.o

all: $(OBJS)

install: $(OBJS)
	mkdir -p ../libraries/OS-Independent/Clean\ System\ Files/
	cp -v $(OBJS) ../libraries/OS-Independent/Clean\ System\ Files/
